on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: sudo apt-get install -y pkg-config libssl-dev mingw-w64
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      - name: Prepare Files
        run: rm target/${{ matrix.target }}/release/rustblood.d && cp target/${{ matrix.target }}/release/rustblood* ./
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: ${{ matrix.archive }}
          filename: ${{ matrix.target }}.${{ matrix.archive }}
          exclusions: '*.git* /*node_modules/* .editorconfig Cargo.toml src/* .github/*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ matrix.target }}.${{ matrix.archive }}
          token: ${{ secrets.GITHUB_TOKEN }}
            