on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: sudo apt-get install -y pkg-config libssl-dev
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          command: build
        args: --target ${{ matrix.target }} --release